package edu.colorado.phet.website.oai

import javax.servlet.ServletContext

/**
 * Metadata conversion to the IMS LODE ILOX metadata format
 *
 * spec: http://lreforschools.eun.org/c/document_library/get_file?p_l_id=10970&folderId=12073&name=DLFE-1.pdf
 * thesaurus: http://demo.lexaurus.net/demo/linkeddata/LRE/LRE-0001/revision/4/attachment
 */
class IMSLODEILOXConverter extends PhetFormatConverter {
  def getToFormat = "ims_lode_ilox" // TODO: what is the metadataPrefix ?

  // TODO: better way of embedding LOM?

  def convertRecord(record: SimulationRecord, servletContext: ServletContext): String = {
    return <work xmlns="http://www.imsglobal.org/xsd/imsloilox_v1p0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.imsglobal.org/xsd/imsloilox_v1p0 http://www.imsglobal.org/xsd/imsloilox_v1p0.xsd">
    <identifier>
        <catalog>phet.colorado.edu</catalog>
        <entry>{record.simPageLink}</entry>
    </identifier>
    <description>
        <facet>
            <vocabularyID>LRE.workDescriptionFacetValues</vocabularyID>
            <value>main</value>
        </facet>
        <metadata>
            <schema>http://ltsc.ieee.org/xsd/LOM</schema>
            <lom xmlns="http://ltsc.ieee.org/xsd/LOM"
                 xsi:schemaLocation="http://ltsc.ieee.org/xsd/LOM http://ltsc.ieee.org/xsd/lomv1.0/lomLoose.xsd">
                <general>
                    <identifier>
                        <catalog>phet.colorado.edu</catalog>
                        <entry>{record.simPageLink}</entry>
                    </identifier>
                    <title>
                        <string language="en">Projectile Motion</string>
                        <string language="ar">حركة المقذوفات</string>
                        <string language="eu">Jaurtigaiaren ibilbidea</string>
                        <string language="pt">Movimento de Projéteis</string>
                        <string language="zh">拋物線運動</string>
                        <string language="hr">Gibanje projektila</string>
                        <string language="cs">projectile-motion</string>
                        <string language="da">Projektil-bevægelser</string>
                        <string language="nl">Beweging projectiel</string>
                        <string language="et">Kehade heitmine</string>
                        <string language="fr">Mouvement d'un projectile</string>
                        <string language="ka">projectile-motion</string>
                        <string language="el">Κίνηση εκτοξευόμενων αντικειμένων</string>
                        <string language="iw">שיגור</string>
                        <string language="hu">Ágyúgolyó futam</string>
                        <string language="it">Moto del proiettile</string>
                        <string language="ja">放物運動</string>
                        <string language="ko">포사체 운동</string>
                        <string language="mk">Движење на проектил</string>
                        <string language="fa">حرکت پرتابه</string>
                        <string language="pl">Rzuty</string>
                        <string language="pt">Lançamento de Projéteis</string>
                        <string language="sr">Кретање пројектила</string>
                        <string language="sk">Pohyb strely</string>
                        <string language="es">projectile-motion</string>
                        <string language="th">การเคลื่อนที่แบบโปรเจคไตล์</string>
                        <string language="tr">projectile-motion</string>
                        <string language="vi">Chuyển động của đạn tử</string>
                    </title>
                    <description>
                        <string language="en">Blast a Buick out of a cannon! Learn about projectile motion by firing various objects. Set
                            the angle, initial speed, and mass. Add air resistance. Make a game out of this simulation by trying to hit a
                            target.
                        </string>
                    </description>
                    <keyword>
                        <string language="en">Projectile Motion</string>
                    </keyword>
                    <keyword>
                        <string language="en">Angle</string>
                    </keyword>
                    <keyword>
                        <string language="en">Initial Speed</string>
                    </keyword>
                    <keyword>
                        <string language="en">Mass</string>
                    </keyword>
                    <keyword>
                        <string language="en">Air Resistance</string>
                    </keyword>
                </general>
                <educational>
                    <learningResourceType>
                        <source>LRE.learningResourceTypeValues</source>
                        <value>simulation</value>
                    </learningResourceType>
                    <intendedEndUserRole>
                        <source>LRE.intendedEndUserRoleValues</source>
                        <value>learner</value>
                    </intendedEndUserRole>
                    <intendedEndUserRole>
                        <source>LRE.intendedEndUserRoleValues</source>
                        <value>teacher</value>
                    </intendedEndUserRole>
                    <context>
                        <source>LRE.contextValues</source>
                        <value>compulsory education</value>
                    </context>
                    <typicalAgeRange>
                        <string language="x-t-lre">12-20</string>
                    </typicalAgeRange>
                </educational>
                <rights>
                    <cost>
                        <source>costValues</source>
                        <value>no</value>
                    </cost>
                    <copyrightAndOtherRestrictions>
                        <source>copyrightAndOtherRestrictionsValues</source>
                        <value>yes</value>
                    </copyrightAndOtherRestrictions>
                    <description>
                        <string language="x-t-cc-url">http://creativecommons.org/licenses/by/3.0/us/</string>
                    </description>
                </rights>
                <classification>
                    <purpose>
                        <source>purposeValues</source>
                        <value>discipline</value>
                    </purpose>
                    <taxonPath>
                        <source>
                            <string language="x-none">LRE-0001</string>
                        </source>
                        <taxon>
                            <id>978</id>
                            <entry>
                                <string language="en">physics</string>
                            </entry>
                        </taxon>
                    </taxonPath>
                </classification>
            </lom>
        </metadata>
    </description>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>en</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion_en.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion_en.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>ar</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_ar.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_ar.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>eu</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_eu.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_eu.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>pt</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_pt_BR.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_pt_BR.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>zh</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_zh_CN.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_zh_CN.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>hr</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_hr.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_hr.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>cs</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_cs.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_cs.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>da</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_da.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_da.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>nl</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_nl.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_nl.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>et</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_et.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_et.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>fr</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_fr.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_fr.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>ka</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_ka.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_ka.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>el</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_el.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_el.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>iw</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_iw.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_iw.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>hu</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_hu.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_hu.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>it</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_it.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_it.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>ja</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_ja.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_ja.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>ko</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_ko.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_ko.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>mk</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_mk.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_mk.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>fa</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_fa.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_fa.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>pl</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_pl.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_pl.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>pt</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_pt.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_pt.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>sr</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_sr.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_sr.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>sk</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_sk.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_sk.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>es</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_es.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_es.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>th</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_th.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_th.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>tr</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_tr.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_tr.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
    <expression>
        <dimension>
            <name>
                <vocabularyID>LRE.expressionDimensionNameValues</vocabularyID>
                <value>language</value>
            </name>
            <parameter>
                <vocabularyID>languageListValues</vocabularyID>
                <value>vi</value>
            </parameter>
        </dimension>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>experience</value>
            </name>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_vi.html</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>package in</value>
            </name>
            <parameter>
                <vocabularyID>LRE.packageInValues</vocabularyID>
                <value>jar</value>
            </parameter>
            <item>
                <location>
                    <uri>/sims/projectile-motion/projectile-motion_vi.jar</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>thumbnail</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/sims/projectile-motion/projectile-motion-screenshot.png</uri>
                </location>
            </item>
        </manifestation>
        <manifestation>
            <name>
                <vocabularyID>LRE.manifestationNameValues</vocabularyID>
                <value>activities guide</value>
            </name>
            <item>
                <location>
                    <uri>http://phet.colorado.edu/en/simulation/projectile-motion</uri>
                </location>
            </item>
        </manifestation>
    </expression>
</work>.toString()
  }
}